- name: Install dependencies
  apt:
    name: curl
    state: present
  become: yes

- name: Download Node Exporter
  get_url:
    url: "{{ node_exporter_download_url }}"
    dest: "/tmp/node_exporter.tar.gz"

- name: Extract Node Exporter
  unarchive:
    src: "/tmp/node_exporter.tar.gz"
    dest: "/tmp"
    remote_src: yes

- name: Move binary to install dir
  command: mv /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter {{ node_exporter_install_dir }}/node_exporter

- name: Set execute permission
  file:
    path: "{{ node_exporter_install_dir }}/node_exporter"
    mode: '0755'


- name: Add systemd service file
  template:
    src: "node_exporter.service.j2"
    dest: "/etc/systemd/system/node_exporter.service"

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Enable and start Node Exporter
  systemd:
    name: node_exporter
    enabled: yes
    state: started
